/**
 * MY Recipes design tokens, ported from the Stitch design files.
 * @type {import('tailwindcss').Config}
 */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'outline-variant': '#c0c9bd',
        'on-secondary-fixed': '#07200f',
        'surface-tint': '#266b3b',
        'inverse-primary': '#90d79c',
        'secondary-fixed-dim': '#b1ceb2',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#ffd9de',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#334d37',
        'primary-fixed': '#abf3b6',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#90d79c',
        'on-primary-fixed-variant': '#035225',
        'tertiary-fixed-dim': '#ffb1bf',
        'on-tertiary-container': '#fffbff',
        'on-surface-variant': '#404940',
        'surface-container-highest': '#e0e3dd',
        'primary-container': '#3e824f',
        'on-surface': '#181d19',
        'tertiary-container': '#ac5c6d',
        'on-secondary-container': '#506b54',
        surface: '#f7faf4',
        secondary: '#4a654e',
        'on-tertiary-fixed': '#3d0416',
        'on-error-container': '#93000a',
        'surface-variant': '#e0e3dd',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#eff2eb',
        'on-primary-fixed': '#00210b',
        'surface-container-high': '#e6e9e3',
        'surface-container': '#ecefe9',
        background: '#f7faf4',
        'secondary-fixed': '#cceacd',
        'surface-bright': '#f7faf4',
        'inverse-surface': '#2d312d',
        'on-tertiary-fixed-variant': '#743041',
        tertiary: '#9aa09a',
        'on-error': '#ffffff',
        'on-background': '#181d19',
        primary: '#236939',
        'on-primary-container': '#f7fff3',
        'surface-container-low': '#f1f5ee',
        'secondary-container': '#cceacd',
        'surface-dim': '#d8dbd5',
        outline: '#707a6f',
        'primary-fixed-variant': '#035225',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        xs: '4px',
        md: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'container-max': '1200px',
        sm: '12px',
        lg: '48px',
        xl: '80px',
        base: '8px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      fontFamily: {
        display: ['Cormorant Garamond', 'serif'],
        headline: ['Cormorant Garamond', 'serif'],
        'headline-lg': ['Cormorant Garamond', 'serif'],
        'headline-lg-mobile': ['Cormorant Garamond', 'serif'],
        'headline-md': ['Cormorant Garamond', 'serif'],
        'headline-sm': ['Cormorant Garamond', 'serif'],
        body: ['Karla', 'sans-serif'],
        'body-lg': ['Karla', 'sans-serif'],
        'body-md': ['Karla', 'sans-serif'],
        'body-sm': ['Karla', 'sans-serif'],
        label: ['Karla', 'sans-serif'],
        'label-lg': ['Karla', 'sans-serif'],
        'label-md': ['Karla', 'sans-serif'],
        'label-sm': ['Karla', 'sans-serif'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-mobile': ['34px', { lineHeight: '42px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
